app:

  app-name: O`Clock
  app-limite-historial: 20

  app-creador: Livington Lopez
  app-creacion: 26-ago-2023
  app-ultima: 26-ago-2023

  app-version: 4.0.0

  modal:
    modal-alarma: Nueva Alarma
    modal-temporizador: Nuevo Temporizador
    modal-crono: Nuevo Cronometro
    modal-reloj: Nuevo Reloj
  
  btn-add:
    btn-alarma: Agregar Alarma
    btn-temporizador: Agregar Temporizador
    btn-crono: Agregar Cronometro
    btn-reloj: Agregar Reloj

  btn-remove:
    btn-alarma: Remover Alarma
    btn-temporizador: Remover Temporizador
    btn-crono: Remover Cronometro
    btn-reloj: Remover Reloj

  