rutas:
  
  # Rutas : 
  # Estas rutas son los archivos de historial, defaults los cuales son listas que tienen diccionarios, los cuales tienen
  # sus propias ID (identificacion o claves privadas), en el contexto de la aplicacion es preferible usar json, en vez de una base
  # de datos, estos archivos tienen un limite de 20 diccionarios en cada listas, ya que quien ensu sano juicio tiene mas de 20 alarmas,
  # temporizadores y cronometros

  historial-temporizador: data/historial/historial_temporizador.json
  historial-alarma: data/historial/historial_alarma.json
  historial-cronometro: data/historial/historial_cronometro.json
  historial-reloj: data/historial/historial_reloj.json
 
 
  # rutas de default 

  credit-sound: data/credit_sounds/creditos.txt
  sound-default: data/d_alarm_sounds/herta singing kururing.mp3
  gif-default: none

  #rutas de otros yaml
  message: reloj/config/message.yaml
  app: reloj/config/app.yaml
